export const CLIMBING_ROCK_OPTIONS = [
  { value: 'limestone', translationKey: 'climbing_rock.limestone' },
  { value: 'sandstone', translationKey: 'climbing_rock.sandstone' },
  { value: 'granite', translationKey: 'climbing_rock.granite' },
  { value: 'quartzite', translationKey: 'climbing_rock.quartzite' },
  { value: 'gneiss', translationKey: 'climbing_rock.gneiss' },
  { value: 'gritstone', translationKey: 'climbing_rock.gritstone' },
  { value: 'porphyry', translationKey: 'climbing_rock.porphyry' },
  { value: 'conglomerate', translationKey: 'climbing_rock.conglomerate' },
  { value: 'basalt', translationKey: 'climbing_rock.basalt' },
  { value: 'slate', translationKey: 'climbing_rock.slate' },
  { value: 'dolomite', translationKey: 'climbing_rock.dolomite' },
  { value: 'concrete', translationKey: 'climbing_rock.concrete' },
  { value: 'puddingstone', translationKey: 'climbing_rock.puddingstone' },
  { value: 'phyllite', translationKey: 'climbing_rock.phyllite' },
  { value: 'artificial', translationKey: 'climbing_rock.artificial' },
  { value: 'ignimbrite', translationKey: 'climbing_rock.ignimbrite' },
  { value: 'schist', translationKey: 'climbing_rock.schist' },
  { value: 'rhyolite', translationKey: 'climbing_rock.rhyolite' },
  { value: 'serpentine', translationKey: 'climbing_rock.serpentine' },
  { value: 'marble', translationKey: 'climbing_rock.marble' },
  { value: 'serpentinite', translationKey: 'climbing_rock.serpentinite' },
  { value: 'chert', translationKey: 'climbing_rock.chert' },
  { value: 'trachyandesite', translationKey: 'climbing_rock.trachyandesite' },
  { value: 'tuff', translationKey: 'climbing_rock.tuff' },
] as const;
