import type { LayerSpecification } from '@maplibre/maplibre-gl-style-spec';

// originaly from basicStyle
export const poiLayers: LayerSpecification[] = [
  {
    id: 'poi-level-3',
    type: 'symbol',
    source: 'maptiler_planet',
    'source-layer': 'poi',
    minzoom: 16,
    filter: [
      'all',
      ['==', '$type', 'Point'],
      ['>=', 'rank', 25],
      ['!=', 'subclass', 'garden'],
      ['!=', 'subclass', 'climbing'],
    ],
    layout: {
      'text-padding': 2,
      'text-font': ['Noto Sans Regular'],
      'text-anchor': 'top',
      'icon-image': '{class}_11',
      'text-field': '{name:latin}\n{name:nonlatin}',
      'text-offset': [0, 0.6],
      'text-size': 12,
      'text-max-width': 9,
    },
    paint: {
      'text-halo-blur': 0.5,
      'text-color': '#666',
      'text-halo-width': 1,
      'text-halo-color': '#ffffff',
    },
  },
  {
    id: 'poi-level-3-gardens',
    type: 'symbol',
    source: 'maptiler_planet',
    'source-layer': 'poi',
    minzoom: 16,
    filter: ['all', ['==', 'subclass', 'garden'], ['has', 'name']],
    layout: {
      'text-padding': 2,
      'text-font': ['Noto Sans Regular'],
      'text-anchor': 'top',
      'icon-image': '{class}_11',
      'text-field': '{name:latin}\n{name:nonlatin}',
      'text-offset': [0, 0.6],
      'text-size': 12,
      'text-max-width': 9,
    },
    paint: {
      'text-halo-blur': 0.5,
      'text-color': '#666',
      'text-halo-width': 1,
      'text-halo-color': '#ffffff',
    },
  },
  {
    id: 'poi-level-2',
    type: 'symbol',
    source: 'maptiler_planet',
    'source-layer': 'poi',
    minzoom: 15,
    filter: [
      'all',
      ['==', '$type', 'Point'],
      ['<=', 'rank', 24],
      ['>=', 'rank', 15],
      ['!=', 'subclass', 'climbing'],
    ],
    layout: {
      'text-padding': 2,
      'text-font': ['Noto Sans Regular'],
      'text-anchor': 'top',
      'icon-image': '{class}_11',
      'text-field': '{name:latin}\n{name:nonlatin}',
      'text-offset': [0, 0.6],
      'text-size': 12,
      'text-max-width': 9,
    },
    paint: {
      'text-halo-blur': 0.5,
      'text-color': '#666',
      'text-halo-width': 1,
      'text-halo-color': '#ffffff',
    },
  },
  {
    id: 'poi-level-1',
    type: 'symbol',
    source: 'maptiler_planet',
    'source-layer': 'poi',
    minzoom: 14,
    filter: [
      'all',
      ['==', '$type', 'Point'],
      ['<=', 'rank', 14],
      ['has', 'name'],
    ],
    layout: {
      'text-padding': 2,
      'text-font': ['Noto Sans Regular'],
      'text-anchor': 'top',
      'icon-image': '{class}_11',
      'text-field': '{name:latin}\n{name:nonlatin}',
      'text-offset': [0, 0.6],
      'text-size': 12,
      'text-max-width': 9,
    },
    paint: {
      'text-halo-blur': 0.5,
      'text-color': '#666',
      'text-halo-width': 1,
      'text-halo-color': '#ffffff',
    },
  },
  {
    id: 'poi-railway',
    type: 'symbol',
    source: 'maptiler_planet',
    'source-layer': 'poi',
    minzoom: 13,
    maxzoom: 24,
    filter: [
      'all',
      ['==', '$type', 'Point'],
      ['has', 'name'],
      ['==', 'class', 'railway'],
      ['==', 'subclass', 'station'],
    ],
    layout: {
      'text-padding': 2,
      'text-font': ['Noto Sans Regular'],
      'text-anchor': 'top',
      'icon-image': '{class}_11',
      'text-field': '{name:latin}\n{name:nonlatin}',
      'text-offset': [0, 0.6],
      'text-size': 12,
      'text-max-width': 9,
      'icon-optional': false,
      'icon-ignore-placement': false,
      'icon-allow-overlap': false,
      'text-ignore-placement': false,
      'text-allow-overlap': false,
      'text-optional': true,
    },
    paint: {
      'text-halo-blur': 0.5,
      'text-color': '#666',
      'text-halo-width': 1,
      'text-halo-color': '#ffffff',
    },
  },
];
