import React from 'react';

// This function doesn't contain any logic - so no extraction needed.
// eslint-disable-next-line max-lines-per-function
export const FaviconsOpenClimbing = () => (
  <>
    <link
      rel="shortcut icon"
      href="/openclimbing/logo/osmapp_192.png"
      sizes="192x192"
    />
    <link
      rel="shortcut icon"
      href="/openclimbing/logo/osmapp_256.png"
      sizes="256x256"
    />
    <link rel="shortcut icon" href="/openclimbing/logo/osmapp_64.png" />
    <link
      rel="shortcut icon"
      href="/openclimbing/favicon.ico"
      type="image/x-icon"
    />
    {/* Generated by https://realfavicongenerator.net/ */}
    <link
      rel="apple-touch-icon"
      sizes="180x180"
      href="/openclimbing/logo/fav/apple-touch-icon.png"
    />{' '}
    {/* apple-touch-icon must have padding + white background */}
    <link
      rel="icon"
      type="image/png"
      sizes="32x32"
      href="/openclimbing/logo/fav/favicon-32x32.png"
    />
    <link
      rel="icon"
      type="image/png"
      sizes="16x16"
      href="/openclimbing/logo/fav/favicon-16x16.png"
    />
    <link
      rel="mask-icon"
      href="/openclimbing/logo/fav/safari-pinned-tab.svg"
      color="#eb5757"
    />{' '}
    {/* For safari tab-favicon */}
    <link rel="manifest" href="/manifest-openclimbing.json" />
    <meta name="application-name" content="OpenClimbing.org" />
    <meta name="apple-mobile-web-app-title" content="OpenClimbing.org" />
    <meta name="theme-color" content="#ffffff" />{' '}
    {/* override for chrome desktop PWA */}
    <meta name="theme-color" content="#eb5757" />{' '}
    {/* HACK: second theme-color is ignored on desktop/mobile, but: makes Android PWA to take the color only from manifest */}
    <meta name="mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta
      name="apple-mobile-web-app-status-bar-style"
      content="black-translucent"
    />{' '}
    <meta name="msapplication-TileColor" content="#9f00a7" />
    <meta
      name="msapplication-config"
      content="/openclimbing/logo/fav/browserconfig.xml"
    />
    {/* splash screens for iOS https://appsco.pe/developer/splash-screens (from osmapp_256.png) */}
    <link
      href="/openclimbing/logo/splash/light/iphone5_splash.png"
      media="(prefers-color-scheme: light) and (device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)"
      rel="apple-touch-startup-image"
    />
    <link
      href="/openclimbing/logo/splash/light/iphone6_splash.png"
      media="(prefers-color-scheme: light) and (device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2)"
      rel="apple-touch-startup-image"
    />
    <link
      href="/openclimbing/logo/splash/light/iphoneplus_splash.png"
      media="(prefers-color-scheme: light) and (device-width: 621px) and (device-height: 1104px) and (-webkit-device-pixel-ratio: 3)"
      rel="apple-touch-startup-image"
    />
    <link
      href="/openclimbing/logo/splash/light/iphonex_splash.png"
      media="(prefers-color-scheme: light) and (device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3)"
      rel="apple-touch-startup-image"
    />
    <link
      href="/openclimbing/logo/splash/light/iphonexr_splash.png"
      media="(prefers-color-scheme: light) and (device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2)"
      rel="apple-touch-startup-image"
    />
    <link
      href="/openclimbing/logo/splash/light/iphonexsmax_splash.png"
      media="(prefers-color-scheme: light) and (device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3)"
      rel="apple-touch-startup-image"
    />
    <link
      href="/openclimbing/logo/splash/light/ipad_splash.png"
      media="(prefers-color-scheme: light) and (device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2)"
      rel="apple-touch-startup-image"
    />
    <link
      href="/openclimbing/logo/splash/light/ipadpro1_splash.png"
      media="(prefers-color-scheme: light) and (device-width: 834px) and (device-height: 1112px) and (-webkit-device-pixel-ratio: 2)"
      rel="apple-touch-startup-image"
    />
    <link
      href="/openclimbing/logo/splash/light/ipadpro3_splash.png"
      media="(prefers-color-scheme: light) and (device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2)"
      rel="apple-touch-startup-image"
    />
    <link
      href="/openclimbing/logo/splash/light/ipadpro2_splash.png"
      media="(prefers-color-scheme: light) and (device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2)"
      rel="apple-touch-startup-image"
    />
    <link
      href="/openclimbing/logo/splash/dark/iphone5_splash.png"
      media="(prefers-color-scheme: dark) and (device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)"
      rel="apple-touch-startup-image"
    />
    <link
      href="/openclimbing/logo/splash/dark/iphone6_splash.png"
      media="(prefers-color-scheme: dark) and (device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2)"
      rel="apple-touch-startup-image"
    />
    <link
      href="/openclimbing/logo/splash/dark/iphoneplus_splash.png"
      media="(prefers-color-scheme: dark) and (device-width: 621px) and (device-height: 1104px) and (-webkit-device-pixel-ratio: 3)"
      rel="apple-touch-startup-image"
    />
    <link
      href="/openclimbing/logo/splash/dark/iphonex_splash.png"
      media="(prefers-color-scheme: dark) and (device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3)"
      rel="apple-touch-startup-image"
    />
    <link
      href="/openclimbing/logo/splash/dark/iphonexr_splash.png"
      media="(prefers-color-scheme: dark) and (device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2)"
      rel="apple-touch-startup-image"
    />
    <link
      href="/openclimbing/logo/splash/dark/iphonexsmax_splash.png"
      media="(prefers-color-scheme: dark) and (device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3)"
      rel="apple-touch-startup-image"
    />
    <link
      href="/openclimbing/logo/splash/dark/ipad_splash.png"
      media="(prefers-color-scheme: dark) and (device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2)"
      rel="apple-touch-startup-image"
    />
    <link
      href="/openclimbing/logo/splash/dark/ipadpro1_splash.png"
      media="(prefers-color-scheme: dark) and (device-width: 834px) and (device-height: 1112px) and (-webkit-device-pixel-ratio: 2)"
      rel="apple-touch-startup-image"
    />
    <link
      href="/openclimbing/logo/splash/dark/ipadpro3_splash.png"
      media="(prefers-color-scheme: dark) and (device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2)"
      rel="apple-touch-startup-image"
    />
    <link
      href="/openclimbing/logo/splash/dark/ipadpro2_splash.png"
      media="(prefers-color-scheme: dark) and (device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2)"
      rel="apple-touch-startup-image"
    />
  </>
);
