import React from 'react';

/*

// ios - pwa maskable icons (white background)
57x57 (iOS)
60x60 (iOS)
72x72 (iOS)
76x76 (iOS)
114x114 (iOS)
120x120 (iOS)
152x152 (iOS)
180x180 (iOS)

// others - pwa maskable icons (transparent)
48x48
96x96
144x144
192x192
256x256
384x384
512x512

*/

export const Favicons = () => (
  <>
    {/* <link rel="shortcut icon" href="/logo/osmapp_192.png" sizes="192x192" /> */}
    {/* <link rel="shortcut icon" href="/logo/osmapp_256.png" sizes="256x256" /> */}
    {/* <link rel="shortcut icon" href="/logo/osmapp_64.png" /> */}
    {/* <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" /> */}
    {/* <link rel="apple-touch-icon" href="/logo/apple/apple.png" /> */}
    {/* <link rel="apple-touch-icon" sizes="57x57" href="/logo/apple/apple_57.png" /> */}
    {/* <link rel="apple-touch-icon" sizes="72x72" href="/logo/apple/apple_72.png" /> */}
    {/* <link rel="apple-touch-icon" sizes="76x76" href="/logo/apple/apple_76.png" /> */}
    {/* <link rel="apple-touch-icon" sizes="114x114" href="/logo/apple/apple_114.png" /> */}
    {/* <link rel="apple-touch-icon" sizes="120x120" href="/logo/apple/apple_120.png" /> */}
    {/* <link rel="apple-touch-icon" sizes="144x144" href="/logo/apple/apple_144.png" /> */}
    {/* <link rel="apple-touch-icon" sizes="152x152" href="/logo/apple/apple_152.png" /> */}
    {/* <link rel="apple-touch-icon" sizes="180x180" href="/logo/apple/apple_180.png" /> */}
    {/* <link rel="apple-touch-icon" sizes="48x48" href="/logo/pwa/maskable_x48.png" /> */}
    {/* <link rel="apple-touch-icon" sizes="72x72" href="/logo/pwa/maskable_x72.png" /> */}
    {/* <link rel="apple-touch-icon" sizes="96x96" href="/logo/pwa/maskable_x96.png" /> */}
    {/* <link rel="apple-touch-icon" sizes="128x128" href="/logo/pwa/maskable_x128.png" /> */}
    {/* <link rel="apple-touch-icon" sizes="192x192" href="/logo/pwa/maskable_x192.png" /> */}
    {/* <link rel="apple-touch-icon" sizes="384x384" href="/logo/pwa/maskable_x384.png" /> */}
    {/* <link rel="apple-touch-icon" sizes="512x512" href="/logo/pwa/maskable_x512.png" /> */}
    {/* Generated by https://realfavicongenerator.net/ */}
    <link
      rel="apple-touch-icon"
      sizes="180x180"
      href="/logo/fav/apple-touch-icon.png"
    />
    <link
      rel="icon"
      type="image/png"
      sizes="32x32"
      href="/logo/fav/favicon-32x32.png"
    />
    <link
      rel="icon"
      type="image/png"
      sizes="16x16"
      href="/logo/fav/favicon-16x16.png"
    />
    <link
      rel="mask-icon"
      href="/logo/fav/safari-pinned-tab.svg"
      color="#5bbad5"
    />
    <link rel="shortcut icon" href="/logo/fav/favicon.ico" />
    <meta name="apple-mobile-web-app-title" content="OsmAPP maps" />
    <meta name="application-name" content="OsmAPP maps" />
    <meta name="msapplication-TileColor" content="#9f00a7" />
    <meta name="msapplication-config" content="/logo/fav/browserconfig.xml" />
    <meta name="theme-color" content="#ffffff" />
    <link rel="manifest" href="/manifest.json" />
    <meta name="theme-color" content="#eb5757" />
    <meta name="description" content="A universal OpenStreetMap app" />
    <meta name="mobile-web-app-capable" content="yes" />
    <meta name="application-name" content="OsmAPP maps" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    {/* TODO try black-translucent and move content 20px down */}
    <meta
      name="apple-mobile-web-app-status-bar-style"
      content="black-translucent"
    />
    <meta name="apple-mobile-web-app-title" content="OsmAPP maps" />
  </>
);
