// Generated by Xata Codegen 0.30.1. Please do not edit.
import { buildClient } from '@xata.io/client';
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from '@xata.io/client';

const tables = [
  {
    name: 'climbing_tiles',
    checkConstraints: {
      climbing_tiles_xata_id_length_xata_id: {
        name: 'climbing_tiles_xata_id_length_xata_id',
        columns: ['xata_id'],
        definition: 'CHECK ((length(xata_id) < 256))',
      },
    },
    foreignKeys: {},
    primaryKey: [],
    uniqueConstraints: {
      _pgroll_new_climbing_tiles_xata_id_key: {
        name: '_pgroll_new_climbing_tiles_xata_id_key',
        columns: ['xata_id'],
      },
    },
    columns: [
      {
        name: 'count',
        type: 'int',
        notNull: false,
        unique: false,
        defaultValue: null,
        comment: '',
      },
      {
        name: 'geohash',
        type: 'text',
        notNull: true,
        unique: false,
        defaultValue: null,
        comment: '',
      },
      {
        name: 'geojson',
        type: 'json',
        notNull: true,
        unique: false,
        defaultValue: null,
        comment: '',
      },
      {
        name: 'lat',
        type: 'float',
        notNull: true,
        unique: false,
        defaultValue: null,
        comment: '',
      },
      {
        name: 'lon',
        type: 'float',
        notNull: true,
        unique: false,
        defaultValue: null,
        comment: '',
      },
      {
        name: 'name',
        type: 'text',
        notNull: false,
        unique: false,
        defaultValue: null,
        comment: '',
      },
      {
        name: 'osmId',
        type: 'int',
        notNull: true,
        unique: false,
        defaultValue: null,
        comment: '',
      },
      {
        name: 'osmType',
        type: 'text',
        notNull: true,
        unique: false,
        defaultValue: null,
        comment: '',
      },
      {
        name: 'type',
        type: 'text',
        notNull: true,
        unique: false,
        defaultValue: null,
        comment: '',
      },
      {
        name: 'xata_createdat',
        type: 'datetime',
        notNull: true,
        unique: false,
        defaultValue: 'now()',
        comment: '',
      },
      {
        name: 'xata_id',
        type: 'text',
        notNull: true,
        unique: true,
        defaultValue: "('rec_'::text || (xata_private.xid())::text)",
        comment: '',
      },
      {
        name: 'xata_updatedat',
        type: 'datetime',
        notNull: true,
        unique: false,
        defaultValue: 'now()',
        comment: '',
      },
      {
        name: 'xata_version',
        type: 'int',
        notNull: true,
        unique: false,
        defaultValue: '0',
        comment: '',
      },
    ],
  },
  {
    name: 'test_xata_cols',
    checkConstraints: {
      test_xata_cols_xata_id_length_xata_id: {
        name: 'test_xata_cols_xata_id_length_xata_id',
        columns: ['xata_id'],
        definition: 'CHECK ((length(xata_id) < 256))',
      },
    },
    foreignKeys: {},
    primaryKey: [],
    uniqueConstraints: {
      _pgroll_new_test_xata_cols_xata_id_key: {
        name: '_pgroll_new_test_xata_cols_xata_id_key',
        columns: ['xata_id'],
      },
    },
    columns: [
      {
        name: 'xata_createdat',
        type: 'datetime',
        notNull: true,
        unique: false,
        defaultValue: 'now()',
        comment: '',
      },
      {
        name: 'xata_id',
        type: 'text',
        notNull: true,
        unique: true,
        defaultValue: "('rec_'::text || (xata_private.xid())::text)",
        comment: '',
      },
      {
        name: 'xata_updatedat',
        type: 'datetime',
        notNull: true,
        unique: false,
        defaultValue: 'now()',
        comment: '',
      },
      {
        name: 'xata_version',
        type: 'int',
        notNull: true,
        unique: false,
        defaultValue: '0',
        comment: '',
      },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type ClimbingTiles = InferredTypes['climbing_tiles'];
export type ClimbingTilesRecord = ClimbingTiles & XataRecord;

export type TestXataCols = InferredTypes['test_xata_cols'];
export type TestXataColsRecord = TestXataCols & XataRecord;

export type DatabaseSchema = {
  climbing_tiles: ClimbingTilesRecord;
  test_xata_cols: TestXataColsRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    'https://osmapp-tvgiad.us-east-1.xata.sh/db/db_with_direct_access',
  apiKey: 'xau_E0h76BAWwiiGCOqEYZsRoCUQqXEQ3jpM',
  branch: 'main',
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
