// Generated by Xata Codegen 0.30.1. Please do not edit.
import { buildClient } from '@xata.io/client';
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from '@xata.io/client';

const tables = [
  {
    name: 'climbing_tiles',
    checkConstraints: {},
    foreignKeys: {},
    primaryKey: ['xata_id'],
    uniqueConstraints: {},
    columns: [
      {
        name: 'count',
        type: 'int',
        notNull: true,
        unique: false,
        defaultValue: null,
        comment: '',
      },
      {
        name: 'geojson',
        type: 'json',
        notNull: true,
        unique: false,
        defaultValue: null,
        comment: '',
      },
      {
        name: 'lat',
        type: 'float',
        notNull: true,
        unique: false,
        defaultValue: null,
        comment: '',
      },
      {
        name: 'lon',
        type: 'float',
        notNull: true,
        unique: false,
        defaultValue: null,
        comment: '',
      },
      {
        name: 'name',
        type: 'text',
        notNull: true,
        unique: false,
        defaultValue: null,
        comment: '',
      },
      {
        name: 'osmId',
        type: 'int',
        notNull: true,
        unique: false,
        defaultValue: null,
        comment: '',
      },
      {
        name: 'osmType',
        type: 'text',
        notNull: true,
        unique: false,
        defaultValue: null,
        comment: '',
      },
      {
        name: 'type',
        type: 'text',
        notNull: true,
        unique: false,
        defaultValue: null,
        comment: '',
      },
      {
        name: 'xata_id',
        type: 'int',
        notNull: true,
        unique: true,
        defaultValue: null,
        comment: '',
      },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type ClimbingTiles = InferredTypes['climbing_tiles'];
export type ClimbingTilesRecord = ClimbingTiles & XataRecord;

export type DatabaseSchema = {
  climbing_tiles: ClimbingTilesRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    'https://osmapp-tvgiad.us-east-1.xata.sh/db/db_with_direct_access',
  apiKey: 'xau_E0h76BAWwiiGCOqEYZsRoCUQqXEQ3jpM',
  branch: 'main',
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
