name: Build & Deploy VPS

on:
  push:
    branches: [master, deploy-vps]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

#      - name: Install dependencies
#        run: yarn install --frozen-lockfile
#
#      - name: Create build env file
#        run: |
#          echo "VERCEL_GIT_COMMIT_SHA=$(git rev-parse HEAD)" >> .env
#          echo "VERCEL_GIT_COMMIT_MESSAGE=$(git log -1 --pretty=%B)" >> .env
#          echo "NEXT_PUBLIC_ENABLE_CLIMBING_TILES=true" >> .env
#
#      - name: Build (standalone)
#        run: NEXTJS_OUTPUT=standalone yarn build
#
#      - name: Restructure standalone output
#        run: |
#          mv public .next/standalone
#          mkdir -p .next/standalone/public/_next
#          mv .next/static .next/standalone/public/_next/

      - uses: actions/upload-artifact@v4
        with:
          name: osmapp-build
          path: .github
#          path: .next/standalone
          include-hidden-files: true

      - name: Trigger deploy webhook with artifact URL
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUN_ID: ${{ github.run_id }}
          REPO: ${{ github.repository }}
        run: |
          ARTIFACTS=$(gh api repos/$REPO/actions/runs/$RUN_ID/artifacts)
          ARTIFACT_URL=$(echo "$ARTIFACTS" | jq '.artifacts[0].archive_download_url')
          echo "ARTIFACTS: $ARTIFACTS"
          echo "ARTIFACT_URL: $ARTIFACT_URL"

          set -x
          curl --insecure https://13.62.127.2/deploy-webhook -X POST -d "$ARTIFACT_URL" --silent --dump-header -

